### ISSUE TITLE
Google Search Console error for /2015/meet.html

### ISSUE THREAD

**Issue by ninjapanzer** [cornerstone-rm/cornerstone-rm.github.io#16]
https://leadwithcornerstone.com/2015/meet.html is listed as a crawl error by google

Check to make sure no links point here and then mark it as fixed in the console `crawl errors`

**Comment by garyanewsome** [comment]
No links point to the address `https://leadwithcornerstone.com/2015/meet.html`. Marked as fixed in `crawl errors` on Google Search Console
