### ISSUE TITLE
Landing page client logos

### ISSUE THREAD

**Issue by ninjapanzer** [cornerstone-rm/cornerstone-rm.github.io#25]
An example is Stitches

**Comment by aloya** [comment]
These are the logos we need to include.
![astrazeneca](https://cloud.githubusercontent.com/assets/6068308/18999897/d83b1dc0-870d-11e6-8895-e7101cfad6fc.png)
![biogen](https://cloud.githubusercontent.com/assets/6068308/18999899/d83fe0e4-870d-11e6-939f-717b8bcb9e4d.png)
![biogenic](https://cloud.githubusercontent.com/assets/6068308/18999898/d83e0fd0-870d-11e6-976d-f29bc45bbabb.png)
![boehringer](https://cloud.githubusercontent.com/assets/6068308/18999900/d8402496-870d-11e6-80ee-e9517f013eda.png)
![emd_serono](https://cloud.githubusercontent.com/assets/6068308/18999902/d8457fc2-870d-11e6-8fee-9a86cbe8cbe6.png)
![gsk](https://cloud.githubusercontent.com/assets/6068308/18999901/d8444206-870d-11e6-8cdd-4f3e17444934.jpg)
![janssen](https://cloud.githubusercontent.com/assets/6068308/18999903/d849b4de-870d-11e6-9185-8ea26ef449bc.png)
![johnsoncontrols](https://cloud.githubusercontent.com/assets/6068308/18999904/d84a9f5c-870d-11e6-927f-d6dda0775bf2.png)
![kci](https://cloud.githubusercontent.com/assets/6068308/18999905/d84da47c-870d-11e6-9f90-dc89d9305dd9.jpg)
![novartis](https://cloud.githubusercontent.com/assets/6068308/18999906/d850ecb8-870d-11e6-87a4-806f301f145f.jpg)
![pitney_bowes](https://cloud.githubusercontent.com/assets/6068308/18999907/d8524d9c-870d-11e6-80ee-0f80c35797c9.jpg)
![regeneron](https://cloud.githubusercontent.com/assets/6068308/18999908/d854572c-870d-11e6-82db-6c9927803a43.jpg)
![roche](https://cloud.githubusercontent.com/assets/6068308/18999909/d859cbda-870d-11e6-908b-a4d7fb236b13.jpg)
![sanofipasteur](https://cloud.githubusercontent.com/assets/6068308/18999912/d85ed49a-870d-11e6-86e0-46dd70c13699.jpg)
![scjohnson](https://cloud.githubusercontent.com/assets/6068308/18999911/d85d0188-870d-11e6-91d6-4b2571c0b4b4.jpg)
![shionogi](https://cloud.githubusercontent.com/assets/6068308/18999910/d85a4dbc-870d-11e6-8a04-5c854b4a02c5.jpg)
![westinghouse_electric](https://cloud.githubusercontent.com/assets/6068308/18999913/d8677fdc-870d-11e6-9fbd-98ea0ba44473.png)

**Comment by ninjapanzer** [comment]
@garyanewsome
here is the next step. I need a block of client logos on the homepage.

I would prefer them to be visible above the fold but the bigger constraint is to size them so they are readable on non retina displays but don't take up too much page space. the script should have sized them 150 height but use your best judgement.
