### ISSUE TITLE
Left padding or margin is making header off center.

### ISSUE THREAD

**Issue by aloya** [cornerstone-rm/cornerstone-rm.github.io#41]
Under Press releases > the left side of pr column has no padding or margin. Its throwing off the header PRESS RELEASE as looking uncentered. The other blocks look to be slightly different widths as well.<img width="1213" alt="screen shot 2016-11-11 at 12 48 14 pm" src="https://cloud.githubusercontent.com/assets/6068308/20224626/5ab8b80a-a80d-11e6-8284-5a347b297c7c.png">

**Comment by garyanewsome** [comment]
So how does one get the fancy box view?

**Comment by aloya** [comment]
web extensions or plugins. in opera its web developer tools. outline block elements. firefox and chrome may have this as extensions as well.

**Comment by garyanewsome** [comment]
I have that!

**Comment by garyanewsome** [comment]
<img width="1183" alt="screen shot 2016-11-11 at 2 05 30 pm" src="https://cloud.githubusercontent.com/assets/13909325/20226892/f4200e4e-a817-11e6-8406-73ff32fb7a64.png">

**Comment by aloya** [comment]
real nice.
