### ISSUE TITLE
White space on top

### ISSUE THREAD

**Issue by aloya** [cornerstone-rm/cornerstone-rm.github.io#42]
After clicking read more on a blog post, the page loads with the header dropped down leaving a white row on top.
<img width="519" alt="screen shot 2016-11-11 at 1 03 12 pm" src="https://cloud.githubusercontent.com/assets/6068308/20225108/9a2409fc-a80f-11e6-9877-8e618f18c095.png">

**Comment by garyanewsome** [comment]
This is a recurring layout issue, due to how the site "floated" the original on top of the body. Just FYI
